CONFIG_OPENBMC_SDBUSPLUS=y
CONFIG_OPENBMC_BOOST=y
CONFIG_OPENBMC_FMT=y
CONFIG_OPENBMC_FUNCTION2=y
CONFIG_OPENBMC_NLOHMANN_JSON=y
CONFIG_OPENBMC_STDPLUS=y
CONFIG_OPENBMC_SDEVENTPLUS=y
CONFIG_OPENBMC_PHOSPHOR_DBUS_INTERFACES=y
CONFIG_OPENBMC_PHOSPHOR_LOGGING=y
CONFIG_OPENBMC_PHOSPHOR_HOST_IPMID=y
CONFIG_OPENBMC_PHOSPHOR_NET_IPMID=y
CONFIG_NETWORKING=y
CONFIG_WOLFSSL=y
CONFIG_WOLFSSL_SETTINGS_FILE="wolfssl_user_settings.h"
CONFIG_TINYXML2=y

CONFIG_CPP=y
CONFIG_REQUIRES_FULL_LIBCPP=y
CONFIG_STD_CPP2B=y
CONFIG_POSIX_API=y
CONFIG_POSIX_TIMERS=y
CONFIG_CPP_EXCEPTIONS=y
CONFIG_GNU_C_EXTENSIONS=y
CONFIG_TOOLCHAIN_CROSS_COMPILE_SUPPORTS_GNU_EXTENSIONS=y

CONFIG_TEST_RANDOM_GENERATOR=y