manifest:

  remotes:
    - name: linkedsemi
      url-base: https://github.com/linkedsemi
      # url-base: git@github.com:linkedsemi

  projects:
    - name: zephyr
      remote: linkedsemi
      revision: openbmc
      import:
        # By using name-allowlist we can clone only the modules that are
        # strictly needed by the application.
        name-allowlist:
          - hal_linkedsemi
    - name: wolfssl
      revision: zephyr
      remote: linkedsemi
      path: modules/lib/wolfssl
    - name: sdbusplus
      revision: zephyr
      remote: linkedsemi
      path: openbmc/sdbusplus
    - name: sdeventplus
      revision: zephyr
      remote: linkedsemi
      path: openbmc/sdeventplus
    - name: stdplus
      revision: zephyr
      remote: linkedsemi
      path: openbmc/stdplus
    - name: nlohmann_json
      revision: zephyr
      remote: linkedsemi
      path: openbmc/nlohmann_json
    - name: fmt
      revision: zephyr
      remote: linkedsemi
      path: openbmc/fmt
    - name: function2
      revision: zephyr
      remote: linkedsemi
      path: openbmc/function2
    - name: phosphor-dbus-interfaces
      revision: zephyr
      remote: linkedsemi
      path: openbmc/phosphor-dbus-interfaces
    - name: phosphor-logging
      revision: zephyr
      remote: linkedsemi
      path: openbmc/phosphor-logging
    - name: phosphor-host-ipmid
      revision: zephyr
      remote: linkedsemi
      path: openbmc/phosphor-host-ipmid
    - name: phosphor-net-ipmid
      revision: zephyr
      remote: linkedsemi
      path: openbmc/phosphor-net-ipmid
    - name: boost
      revision: zephyr
      remote: linkedsemi
      path: openbmc/boost
    - name: tinyxml2
      revision: master
      remote: linkedsemi
      path: modules/lib/tinyxml2