#pragma once

// basic
// #define ENABLE_ZEPHYR_OSAL
#define ENABLE_DBUS_BROKER
#define ENABLE_OPENBMC_PHOSPHOR_OBJMGR
// #define ENABLE_PHOSPHOR_USER_MANAGER
// #define ENABLE_OPENBMC_PHOSPHOR_SETTINGS_MANAGER

// // tools
// #define ENABLE_BUSCTL
// #define ENABLE_OPENBMC_IPMITOOL

// // interfaces
#define ENABLE_OPENBMC_PHOSPHOR_HOST_IPMID
// #define ENABLE_OPENBMC_BMCWEB

// // communication
// #define ENABLE_OPENBMC_IPMBBRIDGE
#define ENABLE_OPENBMC_PHOSPHOR_NET_IPMID
#define ENABLE_OPENBMC_KCSBRIDGE

// // app
// #define ENABLE_OPENBMC_PHOSPHOR_LED_SYSFS
// #define ENABLE_OPENBMC_PHOSPHOR_LED_MANAGER
// #define ENABLE_OPENBMC_PHOSPHOR_WATCHDOG
// #define ENABLE_SYSTEMD_NETWORKD
// #define ENABLE_OPENBMC_PHOSPHOR_NETWORK
// #define ENABLE_OPENBMC_CERTIFICATE_MANAGER
// // #define ENABLE_OPENBMC_OBMC_CONSOLE
// #define ENABLE_OPENBMC_PHOSPHOR_TIME_MANAGER
// #define ENABLE_OPENBMC_BIOS_SETTINGS_MGR
// // #define ENABLE_OPENBMC_PHOSPHOR_BMC_CODE_MGT
#define ENABLE_OPENBMC_PHOSPHOR_LOGGING
#define ENABLE_OPENBMC_DBUS_SENSORS_ADC
#define ENABLE_OPENBMC_DBUS_SENSORS_EXTERNAL
// #define ENABLE_OPENBMC_DBUS_SENSORS_FAN
// #define ENABLE_OPENBMC_DBUS_SENSORS_HWMON_TEMP
// #define ENABLE_OPENBMC_DBUS_SENSORS_INTELCPU
// // #define ENABLE_OPENBMC_DBUS_SENSORS_INTRUSION
// // #define ENABLE_OPENBMC_DBUS_SENSORS_PSU
// #define ENABLE_OPENBMC_PHOSPHOR_SEL_LOGGER
// #define ENABLE_OPENBMC_PHOSPHOR_BMC_STATE_MANAGER
// // #define ENABLE_OPENBMC_PHOSPHOR_DEBUG_COLLECTOR
#define ENABLE_OPENBMC_ENTITY_MANAGER
#define ENABLE_OPENBMC_FRU_DEVICE
// #define ENABLE_OPENBMC_CALLBACK_MANAGER
// // #define ENABLE_OPENBMC_PHOSPHOR_HOSTLOGGER
